<h1>About</h1><br>

<div id = "index">
<h2>Index</h2>
<ul>
  <li>
    <a href = "#introduction">
      Introduction
    </a>
  </li>
  <li>
    <a href = "#howto">
      How it works
    </a>
  </li>
  <li>
    <a href = "#faq">
      FAQ
    </a>
  </li>
  <li>
    <a href = "#terms">
      Terms of Use
    </a>
  </li>
</ul>
</div>

<div id = "contactbox">
  <h2 id = "contact">Contact info</h2>
  <p>Developer: Francisco Presencia Fandos</p>
  <p>Email: admin<span style = "display: none;">none</span>@secretdiary.org</p>
  <p>Development: <a href = "http://github.com/FranciscoP/secretdiary">Fork me on Github</a></p>
</div>

<div style = "clear: both;"></div>

<h2 id = "introduction">Introduction</h2>

<p>You are innocent until proven guilty. Based on this, you deserve privacy in your communications, not to be under surveillance constantly by governments and corporations.</p>

<p>This is a small project on cryptography I have developed just for fun. While I did my best, it might have some bugs. Please feel free to hunt them down and point them out, the code is Open Source and <a href = "http://github.com/FranciscoP/secretdiary">can be found on Github</a>.</p>

<p>For clarity on this page, a <strong>secret</strong> is the message to be hidden, a <strong>door</strong> is the entry point for it where we ask for your <strong>key</strong>, a password. A door has the following format: http://secretdiary.org/ID/ , where the ID is the file id which is stored in the database.</p>

<p><span style = "color: red;">IMPORTANT:</span> The site is not complete, we still do not provide https nor have a certificate. </p>

<h2 id = "howto">How does this page work?</h2>

<h3>Overview</h3>
<p>To <strong>store</strong> the text, we use the password to encrypt the message and save it in the database.
After storing the encrypted text and providing you with a link to it, the password is permanently deleted.</p>
<p>To <strong>retrieve</strong> the text, you enter the link provided and the password.
We retrieve the encrypted text for the link you provided and attempt to decrypt it.</p>

<h3>Detailed description of the process: Encryption.</h3>

<ol>
  <li>
    <p>You <strong>write</strong> and <strong>submit</strong> your text.</p>
  </li>
  <li>
    <p>The <strong>filename</strong> and <strong>password</strong> are autogenerated as hashes (sha1) of strings generated randomly (8 alphanumeric characters) if they are not set by you.</p>
  </li>
  <li>
    <p>The message is encrypted using <strong>MCRYPT_RIJNDAEL_256</strong>, <a href = "http://en.wikipedia.org/wiki/Advanced_Encryption_Standard">the most secure symmetric encryption algorythm</a>.
  </li>
  <li>
    <p>The encrypted text and filename are stored in the database while the password is not.</p>
  </li>
  <li>
    <p>The link for the message is shown but the password is only shown if this was autogenerated. When you navigate away from this page, the password is gone for good.</p>
  </li>
</ol>

<h3>Detailed description of the process: Decryption.</h3>






<p>Relevant: <a href = "http://stackoverflow.com/q/499591/">Are https URLs encrypted?</a></p>

<h3>Tipical uses</h3>
<p>Bob and Alice</p>

<h2 id = "faq">Frequently asked questions</h2>
<p><strong>Q: I forgot my password/key, can I recover it?</strong></p>
<p>A: We are sorry to hear that, but you <strong>cannot</strong> recover it. We simply don't have the means to do so.
If we did, we could read your messages.</p>

<p><strong>Q: Can anyone without the key but with the link to my secret message read it?</strong></p>
<p>A: <strong>No.</strong> All the data is kept encrypted and the key is required for decrypting it.
The data stored in the database is nothign but a bunch of random numbers with little to no value for anyone that doesn't hold the key used originally to encrypt it.</p>

<p><strong>Q: Will you hand over my encrypted message to the authorities if a search warrant is issued?</strong></p>
<p>A: <strong>Yes.</strong> We will abide by the law. This page does not support any illegal act, so we will both hand the encrypted data and delete it from the database if a court order is emited to do so.
However, this is useless data to anyone unless you chose a short, simple password or they have had access to it  (e.g. you stored it in your hard drive and they have also a search warrant for it).</p>

<p><strong>Q: Can YOU read my message?</strong></p>
<p>A: <strong>No.</strong> Read the precedent answer for more information.</p>

<p><strong>Q: Can I use <a href = "http://en.wikipedia.org/wiki/Plausible_deniability" target="_blank">plausible deniability</a> in this site somehow?</strong></p>
<p>A: Actually <strong>yes</strong>. See the <a href = "#howto">howto</a> for more information about how to accomplish this.</p>

<h2 id = "terms">Terms and Conditions</h2>

<p>You must not use this page to do anything illegal.</p>
